matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: hlawWd6ow+jlblL2Ydu0ibxcQyjE0vNFWV+CLDs9Tm8ns5tHAjVQTP+CD5Yp2sbLkuj9tIIRGjoALowra+FQvXcePvYIsghxCK5Dj28BE2FtxZKmFMm2Bgc3Qm9XPOojr+I94FgIqza/SdSkR5yuJWDEFZDpgTTSQm9hKzbcXITtoVMyo+FGImqcWmAJRfZ6/CykdkZD8Rwxc8mtFiLuSQDSVnzwcaH25JXSElJkbQ8mxN7NtpRccXxnNXPuZxiuSHdBJ9IL+9l/Pad/uATXa38G9scdMwyzhwhSLWVqROQ9iTaNm90dRqSnWZXjH1/D5eNupUlJXu3SFqCF8Jn+inDY7mF3j6wxeuM58PYTvn1h9i4mE1ug5g88Sstx9iPvtP39vMcz9CLPWYQIslUQ791uNDtz4YmIIqvJ7DZUk++lxajALyUjBdBlXjMkxYsrtB2uvuAnMBqC8/gm4rPgci+zrWnPmi8bd8b1jbvyZNextu5o6oM+JrJldCZ95rKe+wQmw+Uuft5LH5dMb8nyApbCORNJ4Uj3ByKSNymEqWRA79Zs2JNBZ6Q9+0vDsaSPGm2a8XgYJPKfh+FPimhS6YZRwg9RvYpCZ3jsGgCp8ltRqNXGDm9zLujQ9duEzMZsMWYArIritT8oHivQF8BHpBczBiBpeBZSCtiSJFxfeRY=
