matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: Cantpy0g0dcKemJ8O7WvF+Rcq0D6jOL6I/RtnHkuLuBXNsnorKZtteXWzaYKQwBoKhyfm0t4SIPJvEpV0nad15Px3YUGQEKwVmwp4f6Dt3Qaq9Z600jOBAPXgIVgiVsYNp3ooRv4puHGs3uk2m8GGl+8eFe8EbLJtT/7vVFz5Mrcg9yBJ3QYfwteRq+vaOENYaE8Ys7ggESWANQ81VGcRmyFniCYEI2F+Ek3F31+Em6DyzZmu7eYwH2oHtU0W5qtHUUhlOIOdfhjQENY87Io6YcVt5fwOsTgw3+WetqSLy94/jMlXWUOeGWDvdT0yJjlfMwkz0ZfsMNYh23/fLJPko6vsFUAdSNh5I/Q9rT9IczoAjj/vp0zXUNkD1NvZ0VvJrQXyAeEaNsVjvG4HYczcrErkt4cNIVhfDX56Dnb60csrg0rzO3PS7i/uEj3/9ilR8OZCnfy7DM3JP4y526kGqeXsrOLcxbO+iL/61480vrAQsfJIn7GWhHlhFJt/uRVbvbBWg2ev+DIgwG/HK7f96hykBMkxD/NCADguVn0yLc9z3MpmC9m/p5hD9sGV6uJRitTgXmSAMNQRge/SnLThXmlM6+Ojyl4vlBSci9RlwSKRSWE6LzJ29SiQSSDLvqUV3D94ZGFdNXhu4ydrXblwn4U39sLLJ/110ajOdy4N+s=
